#!/usr/bin/env python
#
# Tweeples - Mine Twitter for people relationships

import json
import os
import sys
import twitter

from twitter.oauth import write_token_file, read_token_file
from twitter.oauth_dance import oauth_dance

def oauth_login(app_name='',
                consumer_key='',
                consumer_secret='',
                token_file='twitter.oauth',
                domain='api.twitter.com'):
    try:
        (access_token, access_token_secret) = read_token_file(token_file)
    except IOError, e:
        (access_token, access_token_secret) = oauth_dance(app_name, consumer_key,
                consumer_secret)

        if not os.path.isdir('out'):
            os.mkdir('out')
        write_token_file(token_file, access_token, access_token_secret)
        print >> sys.stderr, "OAuth Success. Token file stored to", token_file
    return twitter.Twitter(domain=domain, api_version='1',
                        auth=twitter.oauth.OAuth(access_token, access_token_secret,
                        consumer_key, consumer_secret))

if __name__ == '__main__':

    # Go to http://twitter.com/apps/new to create an app and get these items
    # See also http://dev.twitter.com/pages/oauth_single_token

    APP_NAME = 'Tweeple Graph'
    CONSUMER_KEY = ''
    CONSUMER_SECRET = ''

    t = oauth_login(APP_NAME, CONSUMER_KEY, CONSUMER_SECRET,
                    domain='search.twitter.com')
    print '% Authenticated to Twitter'

    # Search for 'freebsd' and print a list of tweets matching.
    search_results = []
    MAX_PAGES = 1
    RESULTS_PER_PAGE = 100
    for page in range(1, MAX_PAGES + 1):
        search_results += (
          t.search(q='freebsd', rpp=RESULTS_PER_PAGE,
                   page=page)['results'])

    print json.dumps(search_results, indent=1)
