#!/usr/bin/env python
#
# Tweeples - Mine Twitter for people relationships

import json
import os
import sys
import twitter

from twitter.oauth import write_token_file, read_token_file
from twitter.oauth_dance import oauth_dance

def oauth_login(app_name='',
                consumer_key='',
                consumer_secret='',
                token_file='twitter.oauth',
                domain='api.twitter.com'):
    try:
        (access_token, access_token_secret) = read_token_file(token_file)
    except IOError, e:
        (access_token, access_token_secret) = oauth_dance(
            app_name, consumer_key, consumer_secret)

        if not os.path.isdir('out'):
            os.mkdir('out')
        write_token_file(token_file, access_token, access_token_secret)
        print >> sys.stderr, "OAuth Success. Token file", token_file
    return twitter.Twitter(domain=domain, api_version='1',
                           auth=twitter.oauth.OAuth(
                               access_token, access_token_secret,
                               consumer_key, consumer_secret))

def search(text, max_pages=10, results_per_page=100):
    while True:
        t = twitter.Twitter(domain="search.twitter.com")

        # Search for 'text' and return a list of tweets matching.
        search_results = []
        for page in range(1, max_pages + 1):
            search_results += (
                t.search(q=text, rpp=results_per_page, page=page)['results'])
        yield search_results

if __name__ == '__main__':

    # Go to http://twitter.com/apps/new to create an app and get these items
    # See also http://dev.twitter.com/pages/oauth_single_token

    APP_NAME = 'Tweeple Graph'
    CONSUMER_KEY = ''				# secret: contact gkeramidas
    CONSUMER_SECRET = ''			# secret: contact 

    lookup_text = 'freebsd'
    for matches in search(lookup_text, max_pages=2, results_per_page=10):
        print json.dumps(matches, indent=1)
        print >> sys.stderr, '%d matches for "%s"\n' % (len(matches),
                                                        lookup_text)
